/********************************************************************************************************************
    iRASPA: GPU-accelated visualisation software for materials scientists
    Copyright (c) 2016-2021 David Dubbeldam, Sofia Calero, Thijs J.H. Vlugt.
    D.Dubbeldam@uva.nl            https://www.uva.nl/en/profile/d/u/d.dubbeldam/d.dubbeldam.html
    S.Calero@tue.nl               https://www.tue.nl/en/research/researchers/sofia-calero/
    t.j.h.vlugt@tudelft.nl        http://homepage.tudelft.nl/v9k6y

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ********************************************************************************************************************/

#include "skelement.h"
#include "rkstring.h"

SKElement::SKElement()
{

}

SKElement::SKElement(RKString string, int64_t atomicNumber, int64_t group, int64_t period, RKString name, double mass, double atomRadius, double covalentRadius, double singleBondCovalentRadius,
          double doubleBondCovalentRadius, double tripleBondCovalentRadius, double vDWRadius, std::vector<int> possibleOxidationStates):
          _chemicalSymbol(string), _atomicNumber(atomicNumber), _group(group), _period(period), _name(name), _mass(mass), _atomRadius(atomRadius), _covalentRadius(covalentRadius),
          _singleBondCovalentRadius(singleBondCovalentRadius), _doubleBondCovalentRadius(doubleBondCovalentRadius), _tripleBondCovalentRadius(tripleBondCovalentRadius),
          _VDWRadius(vDWRadius), _possibleOxidationStates(possibleOxidationStates)
{

}

// van der Waals: https://periodic.lanl.gov/1.shtml
// Van der Waals Radii of Elements, S. S. Batsanov
// https://physlab.lums.edu.pk/images/f/f6/Franck_ref2.pdf
std::vector<SKElement> PredefinedElements::predefinedElements =
{
    //                                                                                    mass         r      cov   1     2     3     vdw
    SKElement(RKString(""),   0,  0,  0, RKString(""),                                      0.0,         0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  std::vector<int>{{}}),
    SKElement(RKString("H"),  1,  1,  1, RKString("Hydrogen"),       1.00794,     0.53,  0.31, 0.32, 0.0,  0.0,  1.20, std::vector<int>{-1,1}),
    SKElement(RKString("He"), 2, 18,  1, RKString("Helium"),         4.002602,    0.31,  0.28, 0.46, 0.0,  0.0,  1.40, std::vector<int>{0}),
    SKElement(RKString("Li"), 3,  1,  2, RKString("Lithium"),        6.9421,      1.67,  1.28, 1.33, 1.24, 0.0,  1.82, std::vector<int>{1}),
    SKElement(RKString("Be"), 4,  2,  3, RKString("Beryllium"),      9.012182,    1.12,  0.96, 1.02, 0.90, 0.85, 1.53, std::vector<int>{1,2}),
    SKElement(RKString("B"),  5,  13, 2, RKString("Boron"),          10.881,      0.87,  0.84, 0.85, 0.78, 0.73, 1.92, std::vector<int>{-5,-1,1,2,3}),
    SKElement(RKString("C"),  6,  14, 2, RKString("Carbon"),         12.0107,     0.67,  0.76, 0.75, 0.67, 0.60, 1.70, std::vector<int>{-4,-3,-2,-1,0,1,2,3,4}),
    SKElement(RKString("N"),  7,  15, 2, RKString("Nitrogen"),       14.0067,     0.56,  0.71, 0.71, 0.60, 0.54, 1.55, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(RKString("O"),  8,  16, 2, RKString("Oxygen"),         15.9994,     0.48,  0.66, 0.63, 0.57, 0.53, 1.52, std::vector<int>{-2,1,1,2}),
    SKElement(RKString("F"),  9,  17, 2, RKString("Fluorine"),       18.9984032,  0.42,  0.57, 0.64, 0.59, 0.53, 1.47, std::vector<int>{-1}),
    SKElement(RKString("Ne"), 10, 18, 2, RKString("Neon"),           20.1797,     0.38,  0.58, 0.67, 0.96, 0.0,  1.54, std::vector<int>{0}),
    SKElement(RKString("Na"), 11,  1, 3, RKString("Sodium"),         22.98976928, 1.90,  1.66, 0.55, 1.60, 0.0,  2.27, std::vector<int>{-1,1}),
    SKElement(RKString("Mg"), 12,  2, 3, RKString("Magnesium"),      24.305,      1.45,  1.41, 1.39, 1.32, 1.27, 1.73, std::vector<int>{1,2}),
    SKElement(RKString("Al"), 13, 13, 3, RKString("Aluminum"),       26.9815386,  1.18,  1.21, 1.26, 1.13, 1.11, 1.84, std::vector<int>{-2,-1,1,2,3}),
    SKElement(RKString("Si"), 14, 14, 3, RKString("Silicon"),        28.0855,     1.11,  1.11, 1.16, 1.07, 1.02, 2.10, std::vector<int>{-4,-3,-2,-1,1,2,3,4}),
    SKElement(RKString("P"),  15, 15, 3, RKString("Phosphorus"),     30.973762,   0.98,  1.07, 1.11, 1.02, 0.94, 1.80, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(RKString("S"),  16, 16, 3, RKString("Sulfur"),         32.065,      0.88,  1.05, 1.03, 0.94, 0.95, 1.80, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(RKString("Cl"), 17, 17, 3, RKString("Chlorine"),       35.453,      0.79,  1.02, 0.99, 0.95, 0.93, 1.75, std::vector<int>{-1,1,2,3,4,5,6,7}),
    SKElement(RKString("Ar"), 18, 18, 3, RKString("Argon"),          39.948,      0.71,  1.06, 0.96, 1.07, 0.96, 1.88, std::vector<int>{0}),
    SKElement(RKString("K"),  19,  1, 4, RKString("Potassium"),      39.0983,     2.43,  2.03, 1.96, 1.93, 0.0,  2.75, std::vector<int>{-1,1}),
    SKElement(RKString("Ca"), 20,  2, 4, RKString("Calcium"),        40.078,      1.94,  1.76, 1.71, 1.47, 1.33, 2.31, std::vector<int>{1,2}),
    SKElement(RKString("Sc"), 21,  3, 4, RKString("Scandium"),       44.955912,   1.84,  1.70, 1.48, 1.16, 1.14, 2.11, std::vector<int>{1,2,3}),
    SKElement(RKString("Ti"), 22,  4, 4, RKString("Titanium"),       47.867,      1.76,  1.60, 1.36, 1.17, 1.08, 1.87, std::vector<int>{-2,-1,1,2,3,4}),
    SKElement(RKString("V"),  23,  5, 4, RKString("Vanadium"),       50.9415,     1.71,  1.53, 1.34, 1.12, 1.06, 1.79, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(RKString("Cr"), 24,  6, 4, RKString("Chromium"),       51.9961,     1.66,  1.39, 1.22, 1.11, 1.03, 1.89, std::vector<int>{-4,-2,-1,1,2,3,4,5,6}),
    SKElement(RKString("Mn"), 25,  7, 4, RKString("Manganese"),      54.939045,   1.61,  1.39, 1.19, 1.05, 1.03, 1.97, std::vector<int>{-3,-2,1,1,2,3,4,5,6,7}),
    SKElement(RKString("Fe"), 26,  8, 4, RKString("Iron"),           55.845,      1.56,  1.32, 1.16, 1.09, 1.02, 1.94, std::vector<int>{-4,-2,-1,1,2,3,4,5,6,7}),
    SKElement(RKString("Co"), 27,  9, 4, RKString("Cobalt"),         58.933195,   1.52,  1.26, 1.11, 1.03, 0.96, 1.92, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(RKString("Ni"), 28, 10, 4, RKString("Nickel"),         58.6934 ,    1.49,  1.24, 1.10, 1.01, 1.01, 1.63, std::vector<int>{-2,-1,1,2,3,4}),
    SKElement(RKString("Cu"), 29, 11, 4, RKString("Copper"),         63.546,      1.45,  1.32, 1.12, 1.15, 1.2,  1.40, std::vector<int>{-2,1,2,3,4}),
    SKElement(RKString("Zn"), 30, 12, 4, RKString("Zinc"),           65.38,       1.42,  1.22, 1.18, 1.20, 0.0,  1.39, std::vector<int>{-2,0,1,2}),
    SKElement(RKString("Ga"), 31, 13, 4, RKString("Gallium"),        69.723,      1.36,  1.22, 1.24, 1.17, 1.21, 1.87, std::vector<int>{-5,-4,-2,-1,1,2,3}),
    SKElement(RKString("Ge"), 32, 14, 4,RKString("Germanium"),       72.64,       1.25,  1.20, 1.21, 1.11, 1.14, 2.11, std::vector<int>{-4,-3,-2,-1,0,1,2,3,4}),
    SKElement(RKString("As"), 33, 15, 4, RKString("Arsenic"),        74.9216,     1.14,  1.19, 1.21, 1.14, 1.06, 1.85, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(RKString("Se"), 34, 16, 3, RKString("Selenium"),       78.96,       1.03,  1.20, 1.16, 1.07, 1.07, 1.90, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(RKString("Br"), 35, 17, 4, RKString("Bromine"),        79.904,      0.94,  1.20, 1.14, 1.09, 1.10, 1.85, std::vector<int>{-1,1,3,4,5,7}),
    SKElement(RKString("Kr"), 36, 18, 4, RKString("Krypton"),        83.798,      0.88,  1.16, 1.17, 1.21, 1.08, 2.02, std::vector<int>{0,1,2}),
    SKElement(RKString("Rb"), 37,  1, 5, RKString("Rubidium"),       85.4678,     2.65,  2.20, 2.10, 2.02, 0.0,  3.03, std::vector<int>{-1,1}),
    SKElement(RKString("Sr"), 38,  2, 5, RKString("Strontium"),      87.62,       2.19,  1.95, 1.85, 1.57, 1.39, 2.49, std::vector<int>{1,2}),
    SKElement(RKString("Y"),  39,  3, 5, RKString("Yttrium"),        88.90585,    2.12,  1.90, 1.63, 1.30, 1.24, 2.19, std::vector<int>{1,2,3}),
    SKElement(RKString("Zr"), 40,  4, 5, RKString("Zirconium"),      91.224,      2.06,  1.75, 1.54, 1.27, 1.21, 1.86, std::vector<int>{-2,1,2,3,4}),
    SKElement(RKString("Nb"), 41,  5, 5, RKString("Niobium"),        92.90638,    1.98,  1.64, 1.47, 1.25, 1.16, 2.07, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(RKString("Mo"), 42,  6, 5, RKString("Molybdenum"),     95.96,       1.90,  1.54, 1.38, 1.21, 1.13, 2.09, std::vector<int>{-4,-2,-1,1,2,3,4,5,6}),
    SKElement(RKString("Tc"), 43,  7, 5, RKString("Technetium"),     98,          1.83,  1.47, 1.28, 1.20, 1.10, 2.09, std::vector<int>{-3,-1,1,2,3,4,5,6,7}),
    SKElement(RKString("Ru"), 44,  8, 5, RKString("Ruthenium"),      101.07,      1.78,  1.46, 1.25, 1.14, 1.03, 2.07, std::vector<int>{-4,-2,1,2,3,4,5,6,7,8}),
    SKElement(RKString("Rh"), 45,  9, 5, RKString("Rhodium"),        102.59055,   1.73,  1.42, 1.25, 1.10, 1.06, 1.95, std::vector<int>{-3,-1,1,2,3,4,5,6}),
    SKElement(RKString("Pd"), 46, 10, 5, RKString("Palladium"),      106.42,      1.69,  1.39, 1.20, 1.17, 1.12, 1.63, std::vector<int>{0,1,2,3,4}),
    SKElement(RKString("Ag"), 47, 11, 5, RKString("Silver"),         107.8682,    1.65,  1.45, 1.28, 1.39, 1.37, 1.72, std::vector<int>{-2,-1,1,2,3}),
    SKElement(RKString("Cd"), 48, 12, 5, RKString("Cadmium"),        112.411,     1.61,  1.44, 1.36, 1.44, 0.0,  1.58, std::vector<int>{-2,1,2}),
    SKElement(RKString("In"), 49, 13, 5, RKString("Indium"),         114.818,     1.56,  1.42, 1.42, 1.36, 1.46, 1.93, std::vector<int>{-5,-2,-1,1,2,3}),
    SKElement(RKString("Sn"), 50, 14, 5, RKString("Tin"),            118.71,      1.45,  1.39, 1.40, 1.30, 1.32, 2.17, std::vector<int>{-4,-3,-2,-1,1,2,3,4}),
    SKElement(RKString("Sb"), 51, 15, 5, RKString("Antimony"),       121.76,      1.33,  1.39, 1.40, 1.33, 1.27, 2.06, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(RKString("Te"), 52, 16, 5, RKString("Tellurium"),      127.6,       1.23,  1.38, 1.36, 1.28, 1.21, 2.06, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(RKString("I"),  53, 17, 5, RKString("Iodine"),         126.90447,   1.15,  1.39, 1.33, 1.29, 1.25, 1.98, std::vector<int>{-1,1,3,4,5,6,7}),
    SKElement(RKString("Xe"), 54, 18, 5, RKString("Xenon"),          131.293,     1.08,  1.40, 1.31, 1.35, 1.22, 2.16, std::vector<int>{0,1,2,4,6,8}),
    SKElement(RKString("Cs"), 55,  1, 6, RKString("Cesium"),         132.9054519, 2.98,  2.44, 2.32, 2.09, 0.0,  3.43, std::vector<int>{-1,1}),
    SKElement(RKString("Ba"), 56,  2, 6, RKString("Barium"),         137.327,     2.53,  2.15, 1.96, 1.61, 1.49, 2.68, std::vector<int>{1,2}),
    SKElement(RKString("La"), 57, -1, 6, RKString("Lanthanum"),      138.90547,   2.26,  2.07, 1.80, 1.39, 1.39, 2.40, std::vector<int>{1,2,3}),
    SKElement(RKString("Ce"), 58, -1, 6, RKString("Cerium"),         140.116,     2.10,  2.04, 1.63, 1.37, 1.31, 2.35, std::vector<int>{1,2,3,4}),
    SKElement(RKString("Pr"), 59, -1, 6, RKString("Praseodymium"),   140.90765,   2.47,  2.03, 1.76, 1.38, 1.28, 2.39, std::vector<int>{2,3,4,5}),
    SKElement(RKString("Nd"), 60, -1, 6, RKString("Neodymium"),      144.242,     2.06,  2.01, 1.74, 1.37, 0.0,  2.29, std::vector<int>{2,3,4}),
    SKElement(RKString("Pm"), 61, -1, 6, RKString("Promethium"),     145,         2.05,  1.99, 1.73, 1.35, 0.0,  2.36, std::vector<int>{2,3}),
    SKElement(RKString("Sm"), 62, -1, 6, RKString("Samarium"),       150.36,      2.38,  1.98, 1.72, 1.34, 0.0,  2.29, std::vector<int>{1,2,3,4}),
    SKElement(RKString("Eu"), 63, -1, 6, RKString("Europium"),       151.964,     2.31,  1.98, 1.68, 1.34, 0.0,  2.33, std::vector<int>{1,2,3}),
    SKElement(RKString("Gd"), 64, -1, 6, RKString("Gadolinium"),     157.25,      2.33,  1.96, 1.68, 1.35, 1.32, 2.37, std::vector<int>{1,2,3}),
    SKElement(RKString("Tb"), 65, -1, 6, RKString("Terbium"),        158.92535,   2.25,  1.94, 1.68, 1.35, 0.0,  2.21, std::vector<int>{1,2,3,4}),
    SKElement(RKString("Dy"), 66, -1, 6, RKString("Dysprosium"),     162.5,       2.28,  1.92, 1.67, 1.33, 0.0,  2.29, std::vector<int>{1,2,3,4}),
    SKElement(RKString("Ho"), 67, -1, 6, RKString("Holmium"),        164.93032,   2.26,  1.92, 1.66, 1.33, 0.0,  2.16, std::vector<int>{1,2,3}),
    SKElement(RKString("Er"), 68, -1, 6, RKString("Erbium"),         167.259,     2.26,  1.89, 1.65, 1.33, 0.0,  2.35, std::vector<int>{1,2,3}),
    SKElement(RKString("Tm"), 69, -1, 6, RKString("Thulium"),        168.93421,   2.22,  1.90, 1.64, 1.31, 0.0,  2.27, std::vector<int>{2,3}),
    SKElement(RKString("Yb"), 70, -1, 6, RKString("Ytterbium"),      173.054,     2.22,  1.87, 1.70, 1.29, 0.0,  2.42, std::vector<int>{1,2,3}),
    SKElement(RKString("Lu"), 71,  3, 6, RKString("Lutetium"),       174.9668,    2.17,  1.75, 1.62, 1.31, 1.31, 2.21, std::vector<int>{1,2,3}),
    SKElement(RKString("Hf"), 72,  4, 6, RKString("Hafnium"),        178.49,      2.08,  1.87, 1.52, 1.28, 1.22, 2.12, std::vector<int>{-2,1,2,3,4}),
    SKElement(RKString("Ta"), 73,  5, 6, RKString("Tantalum"),       180.94788,   2.00,  1.70, 1.46, 1.26, 1.19, 2.17, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(RKString("W"),  74,  6, 6, RKString("Tungsten"),       183.84,      1.93,  1.62, 1.37, 1.20, 1.15, 2.10, std::vector<int>{-4,-2,-1,0,1,2,3,4,5,6}),
    SKElement(RKString("Re"), 75,  7, 6, RKString("Rhenium"),        186.207,     1.88,  1.51, 1.31, 1.19, 1.10, 2.17, std::vector<int>{-3,-1,0,1,2,3,4,5,6,7}),
    SKElement(RKString("Os"), 76,  8, 6, RKString("Osmium"),         190.23,      1.85,  1.44, 1.29, 1.16, 1.09, 2.16, std::vector<int>{-4,-2,0,1,2,3,4,5,6,7,8}),
    SKElement(RKString("Ir"), 77,  9, 6, RKString("Iridium"),        192.217,     1.90,  1.41, 1.22, 1.15, 1.07, 2.02, std::vector<int>{-3,-1,0,1,2,3,4,5,6,7,8,9}),
    SKElement(RKString("Pt"), 78, 10, 6, RKString("Platinum"),       195.084,     1.77,  1.36, 1.23, 1.12, 1.10, 1.75, std::vector<int>{-3,-2,-1,2,3,4,5,6}),
    SKElement(RKString("Au"), 79, 11, 6, RKString("Gold"),           196.966569,  1.74,  1.36, 1.24, 1.21, 1.23, 1.66, std::vector<int>{-3,-2,-1,1,2,3,5}),
    SKElement(RKString("Hg"), 80, 12, 6, RKString("Mercury"),        200.59,      1.71,  1.32, 1.33, 1.42, 0.0,  1.55, std::vector<int>{-2,1,2}),
    SKElement(RKString("Tl"), 81, 13, 6, RKString("Thallium"),       204.3833,    1.56,  1.45, 1.44, 1.42, 1.50, 1.96, std::vector<int>{-5,-2,-1,1,2,3}),
    SKElement(RKString("Pb"), 82, 14, 6, RKString("Lead"),           207.2,       1.54,  1.46, 1.44, 1.35, 1.37, 2.02, std::vector<int>{-4,-2,-1,2,3,4}),
    SKElement(RKString("Bi"), 83, 15, 6, RKString("Bismuth"),        208.9804,    1.43,  1.48, 1.51, 1.41, 1.35, 2.07, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(RKString("Po"), 84, 16, 6, RKString("Polonium"),       210,         1.35,  1.40, 1.45, 1.35, 1.29, 1.97, std::vector<int>{-2,2,4,5,6}),
    SKElement(RKString("At"), 85, 17, 6, RKString("Astatine"),       210.8,       1.27,  1.50, 1.47, 1.38, 1.38, 2.02, std::vector<int>{-1,1,3,5,7}),
    SKElement(RKString("Rn"), 86, 18, 6, RKString("Radon"),          222,         1.20,  1.50, 1.42, 1.45, 1.33, 2.20, std::vector<int>{0,2,6}),
    SKElement(RKString("Fr"),  87,  1, 7, RKString("Francium"),      223,         0.0,   2.60, 2.23, 2.18, 0.0,  3.48, std::vector<int>{1}),
    SKElement(RKString("Ra"),  88,  2, 7, RKString("Radium"),        226,         0.0,   2.21, 2.01, 1.73, 1.59, 2.83, std::vector<int>{2}),
    SKElement(RKString("Ac"),  89, -1, 7, RKString("Actinium"),      227,         0.0,   2.15, 1.86, 1.53, 1.40, 2.60, std::vector<int>{2,3}),
    SKElement(RKString("Th"),  90, -1, 7, RKString("Thorium"),       232.03806,   0.0,   2.06, 1.75, 1.43, 1.36, 2.37, std::vector<int>{1,2,3,4}),
    SKElement(RKString("Pa"),  91, -1, 7, RKString("Protactinium"),  231.03588,   1.63,  2.00, 1.69, 1.38, 1.29, 2.43, std::vector<int>{2,3,4,5}),
    SKElement(RKString("U"),   92, -1, 7, RKString("Uranium"),       238.02891,   1.56,  1.96, 1.70, 1.34, 1.18, 2.40, std::vector<int>{1,2,3,4,5,6}),
    SKElement(RKString("Np"),  93, -1, 7, RKString("Neptunium"),     237,         1.55,  1.90, 1.71, 1.36, 1.16, 2.21, std::vector<int>{2,3,4,5,6,7}),
    SKElement(RKString("Pu"),  94, -1, 7, RKString("Plutonium"),     244,         1.59,  1.87, 1.72, 1.35, 0.0,  2.43, std::vector<int>{1,2,3,4,5,6,7,8}),
    SKElement(RKString("Am"),  95, -1, 7, RKString("Americium"),     243,         1.73,  1.80, 1.66, 1.35, 0.0,  2.44, std::vector<int>{2,3,4,5,6,7,8}),
    SKElement(RKString("Cm"),  96, -1, 7, RKString("Curium"),        247,         1.74,  1.69, 1.66, 1.36, 0.0,  2.45, std::vector<int>{2,3,4,6}),
    SKElement(RKString("Bk"),  97, -1, 7, RKString("Berkelium"),     247,         1.7,   0.0,  1.68, 1.39, 0.0,  2.44, std::vector<int>{2,3,4}),
    SKElement(RKString("Cf"),  98, -1, 7, RKString("Californium"),   251,         0.0,   0.0,  1.68, 1.40, 0.0,  2.45, std::vector<int>{2,3,4}),
    SKElement(RKString("Es"),  99, -1, 7, RKString("Einsteinium"),   252,         0.0,   0.0,  1.65, 1.40, 0.0,  2.45, std::vector<int>{2,3,4}),
    SKElement(RKString("Fm"), 100, -1, 7, RKString("Fermium"),       257,         0.0,   0.0,  1.67, 0.0,  0.0,  0.0,  std::vector<int>{2,3}),
    SKElement(RKString("Md"), 101, -1, 7, RKString("Mendelevium"),   258,         0.0,   0.0,  1.73, 1.39, 0.0,  0.0,  std::vector<int>{2,3}),
    SKElement(RKString("No"), 102, -1, 7, RKString("Nobelium"),      259,         0.0,   0.0,  1.76, 0.0,  0.0,  0.0,  std::vector<int>{2,3}),
    SKElement(RKString("Lr"), 103,  3, 7, RKString("Lawrencium"),    262,         0.0,   0.0,  1.61, 1.41, 0.0,  0.0,  std::vector<int>{3}),
    SKElement(RKString("Rf"), 104,  4, 7, RKString("Rutherfordium"), 261,         0.0,   0.0,  1.57, 1.40, 1.31, 0.0,  std::vector<int>{2,3,4}),
    SKElement(RKString("Db"), 105,  5, 7, RKString("Dubnium"),       268,         1.39,  1.49, 1.49, 1.36, 1.26, 0.0,  std::vector<int>{3,4,5}),
    SKElement(RKString("Sg"), 106,  6, 7, RKString("Seaborgium"),    269,         1.32,  1.43, 1.43, 1.28, 1.21, 0.0,  std::vector<int>{3,4,5,6}),
    SKElement(RKString("Bh"), 107,  7, 7, RKString("Bohrium"),       270,         1.28,  1.41, 1.41, 1.28, 1.19, 0.0,  std::vector<int>{3,4,5,7}),
    SKElement(RKString("Hs"), 108,  8, 7, RKString("Hassium"),       269,         1.26,  1.34, 1.34, 1.25, 1.18, 0.0,  std::vector<int>{2,3,4,5,6,8}),
    SKElement(RKString("Mt"), 109,  9, 7, RKString("Meitnerium"),    278,         1.28,  1.29, 1.29, 1.25, 1.13, 0.0,  std::vector<int>{1,3,4,6,8,9}),
    SKElement(RKString("Ds"), 110, 10, 7, RKString("Darmstadtium"),  281,         1.32,  1.28, 1.28, 1.16, 1.12, 0.0,  std::vector<int>{0,2,4,6,8}),
    SKElement(RKString("Rg"), 111, 11, 7, RKString("Roentgenium"),   281,         1.38,  1.21, 1.21, 1.16, 1.18, 0.0,  std::vector<int>{-1,1,3,5}),
    SKElement(RKString("Cn"), 112, 12, 7, RKString("Copernicium"),   285,         1.47,  1.22, 1.22, 1.37, 1.30, 0.0,  std::vector<int>{0,1,2}),
    SKElement(RKString("Nh"), 113, 13, 7, RKString("Nihonium"),      286,         1.70,  1.76, 1.36, 0.0,  0.0,  0.0,  std::vector<int>{-1,1,3,5}),
    SKElement(RKString("Fl"), 114, 14, 7, RKString("Flerovium"),     289,         1.80,  1.74, 1.43, 0.0,  0.0,  0.0,  std::vector<int>{0,1,2,4,6}),
    SKElement(RKString("Mc"), 115, 15, 7, RKString("Moscovium"),     288,         1.87,  1.57, 1.62, 0.0,  0.0,  0.0,  std::vector<int>{1,3}),
    SKElement(RKString("Lv"), 116, 16, 7, RKString("Livermorium"),   293,         1.83,  1.64, 1.75, 0.0,  0.0,  0.0,  std::vector<int>{-2,2,4}),
    SKElement(RKString("Ts"), 117, 17, 7, RKString("Tennessine"),    294,         1.38,  1.56, 1.65, 0.0,  0.0,  0.0,  std::vector<int>{-1,1,3,5}),
    SKElement(RKString("Og"), 118, 18, 7, RKString("Oganesson"),     294,         1.52,  1.57, 1.57, 0.0,  0.0,  0.0,  std::vector<int>{-1,0,1,2,4,6})
};

std::map<RKString, int> PredefinedElements::atomicNumberData =
{
    {RKString("H"), 1}, {RKString("He"), 2}, {RKString("Li"), 3}, {RKString("Be"), 4}, {RKString("B"), 5}, {RKString("C"), 6}, {RKString("N"), 7}, {RKString("O"), 8}, {RKString("F"), 9},
    {RKString("Ne"), 10}, {RKString("Na"), 11}, {RKString("Mg"), 12}, {RKString("Al"), 13}, {RKString("Si"), 14}, {RKString("P"), 15}, {RKString("S"), 16,}, {RKString("Cl"), 17}, {RKString("Ar"), 18}, {RKString("K"), 19},
    {RKString("Ca"), 20}, {RKString("Sc"), 21}, {RKString("Ti"), 22}, {RKString("V"), 23}, {RKString("Cr"), 24}, {RKString("Mn"), 25}, {RKString("Fe"), 26}, {RKString("Co"), 27}, {RKString("Ni"), 28}, {RKString("Cu"), 29},
    {RKString("Zn"), 30}, {RKString("Ga"), 31}, {RKString("Ge"), 32}, {RKString("As"), 33}, {RKString("Se"), 34,}, {RKString("Br"), 35}, {RKString("Kr"), 36}, {RKString("Rb"), 37}, {RKString("Sr"), 38}, {RKString("Y"), 39},
    {RKString("Zr"), 40}, {RKString("Nb"), 41}, {RKString("Mo"), 42}, {RKString("Tc"), 43}, {RKString("Ru"), 44}, {RKString("Rh"), 45}, {RKString("Pd"), 46}, {RKString("Ag"), 47}, {RKString("Cd"), 48}, {RKString("In"), 49},
    {RKString("Sn"), 50}, {RKString("Sb"), 51}, {RKString("Te"), 52}, {RKString("I"), 53}, {RKString("Xe"), 54}, {RKString("Cs"), 55}, {RKString("Ba"), 56}, {RKString("La"), 57}, {RKString("Ce"), 58}, {RKString("Pr"), 59},
    {RKString("Nd"), 60}, {RKString("Pm"), 61}, {RKString("Sm"), 62}, {RKString("Eu"), 63}, {RKString("Gd"), 64}, {RKString("Tb"), 65}, {RKString("Dy"), 66}, {RKString("Ho"), 67}, {RKString("Er"), 68}, {RKString("Tm"), 69},
    {RKString("Yb"), 70}, {RKString("Lu"), 71}, {RKString("Hf"), 72}, {RKString("Ta"), 73}, {RKString("W"), 74}, {RKString("Re"), 75}, {RKString("Os"), 76}, {RKString("Ir"), 77}, {RKString("Pt"), 78}, {RKString("Au"), 79},
    {RKString("Hg"), 80}, {RKString("Tl"), 81}, {RKString("Pb"), 82}, {RKString("Bi"), 83}, {RKString("Po"), 84}, {RKString("At"), 85}, {RKString("Rn"), 86}, {RKString("Fr"), 87}, {RKString("Ra"), 88}, {RKString("Ac"), 89},
    {RKString("Th"), 90}, {RKString("Pa"), 91}, {RKString("U"), 92}, {RKString("Np"), 93}, {RKString("Pu"), 94}, {RKString("Am"), 95}, {RKString("Cm"), 96}, {RKString("Bk"), 97}, {RKString("Cf"), 98}, {RKString("Es"), 99},
    {RKString("Fm"), 100}, {RKString("Md"), 101}, {RKString("No"), 102}, {RKString("Lr"), 103}, {RKString("Rf"), 104}, {RKString("Db"), 105}, {RKString("Sg"), 106}, {RKString("Bh"), 107}, {RKString("Hs"), 108}, {RKString("Mt"), 109},
    {RKString("Ds"), 110}, {RKString("Rg"), 111}, {RKString("Cn"), 112}, {RKString("Nh"), 113}, {RKString("Fl"), 114}, {RKString("Mc"), 115}, {RKString("Lv"), 116}, {RKString("Ts"), 117}, {RKString("Og"), 118}
};

std::set<RKString> PredefinedElements::residueDefinitions =
{
  RKString("ALA"),
  RKString("ARG"),
  RKString("ASN"),
  RKString("ASP"),
  RKString("CYS"),
  RKString("GLN"),
  RKString("GLU"),
  RKString("GLY"),
  RKString("HIS"),
  RKString("HOH"),
  RKString("ILE"),
  RKString("LEU"),
  RKString("LYS"),
  RKString("MET"),
  RKString("PHE"),
  RKString("PRO"),
  RKString("SER"),
  RKString("THR"),
  RKString("TRP"),
  RKString("TYR"),
  RKString("VAL")
};

std::map<RKString, RKString> PredefinedElements::residueDefinitionsElement =
{
  {RKString("ALA+C")    ,"C"},
  {RKString("ALA+CA")   ,"C"},
  {RKString("ALA+CB")   ,"C"},
  {RKString("ALA+N")    ,"N"},
  {RKString("ALA+O")    ,"O"},
  {RKString("ALA+OXT")  ,"O"},
  {RKString("ALA+H")    ,"H"},
  {RKString("ALA+HA")   ,"H"},
  {RKString("ALA+HB1")  ,"H"},
  {RKString("ALA+HB2")  ,"H"},
  {RKString("ALA+HB3")  ,"H"},

  {RKString("ARG+C")    ,"C"},
  {RKString("ARG+CA")   ,"C"},
  {RKString("ARG+CB")   ,"C"},
  {RKString("ARG+CD")   ,"C"},
  {RKString("ARG+CG")   ,"C"},
  {RKString("ARG+CZ")   ,"C"},
  {RKString("ARG+N")    ,"N"},
  {RKString("ARG+NE")   ,"N"},
  {RKString("ARG+NH1")  ,"N"},
  {RKString("ARG+NH2")  ,"N"},
  {RKString("ARG+O")    ,"O"},
  {RKString("ARG+OXT")  ,"O"},
  {RKString("ARG+H")    ,"H"},
  {RKString("ARG+HA")   ,"H"},
  {RKString("ARG+HB2")  ,"H"},
  {RKString("ARG+HB3")  ,"H"},
  {RKString("ARG+HD2")  ,"H"},
  {RKString("ARG+HD3")  ,"H"},
  {RKString("ARG+HE")   ,"H"},
  {RKString("ARG+HG2")  ,"H"},
  {RKString("ARG+HG3")  ,"H"},
  {RKString("ARG+HH11") ,"H"},
  {RKString("ARG+HH12") ,"H"},
  {RKString("ARG+HH21") ,"H"},
  {RKString("ARG+HH22") ,"H"},

  {RKString("ASN+C")    ,"C"},
  {RKString("ASN+CA")   ,"C"},
  {RKString("ASN+CB")   ,"C"},
  {RKString("ASN+CG")   ,"C"},
  {RKString("ASN+N")    ,"N"},
  {RKString("ASN+ND2")  ,"N"},
  {RKString("ASN+O")    ,"O"},
  {RKString("ASN+OD1")  ,"O"},
  {RKString("ASN+OXT")  ,"O"},
  {RKString("ASN+H")    ,"H"},
  {RKString("ASN+HA")   ,"H"},
  {RKString("ASN+HB2")  ,"H"},
  {RKString("ASN+HB3")  ,"H"},
  {RKString("ASN+HD21") ,"H"},
  {RKString("ASN+HD22") ,"H"},

  {RKString("ASP+C")    ,"C"},
  {RKString("ASP+CA")   ,"C"},
  {RKString("ASP+CB")   ,"C"},
  {RKString("ASP+CG")   ,"C"},
  {RKString("ASP+N")    ,"N"},
  {RKString("ASP+O")    ,"O"},
  {RKString("ASP+OD1")  ,"O"},
  {RKString("ASP+OD2")  ,"O"},
  {RKString("ASP+OXT")  ,"O"},
  {RKString("ASP+H")    ,"H"},
  {RKString("ASP+HA")   ,"H"},
  {RKString("ASP+HB2")  ,"H"},
  {RKString("ASP+HB3")  ,"H"},

  {RKString("CYS+C")    ,"C"},
  {RKString("CYS+CA")   ,"C"},
  {RKString("CYS+CB")   ,"C"},
  {RKString("CYS+N")    ,"N"},
  {RKString("CYS+O")    ,"O"},
  {RKString("CYS+SG")   ,"S"},
  {RKString("CYS+OXT")  ,"O"},
  {RKString("CYS+H")    ,"H"},
  {RKString("CYS+HA")   ,"H"},
  {RKString("CYS+HB2")  ,"H"},
  {RKString("CYS+HB3")  ,"H"},

  {RKString("GLN+C")    ,"C"},
  {RKString("GLN+CA")   ,"C"},
  {RKString("GLN+CB")   ,"C"},
  {RKString("GLN+CD")   ,"C"},
  {RKString("GLN+CG")   ,"C"},
  {RKString("GLN+N")    ,"N"},
  {RKString("GLN+NE2")  ,"N"},
  {RKString("GLN+O")    ,"O"},
  {RKString("GLN+OE1")  ,"O"},
  {RKString("GLN+OXT")  ,"O"},
  {RKString("GLN+H")    ,"H"},
  {RKString("GLN+HA")   ,"H"},
  {RKString("GLN+HB2")  ,"H"},
  {RKString("GLN+HB3")  ,"H"},
  {RKString("GLN+HG2")  ,"H"},
  {RKString("GLN+HG3")  ,"H"},
  {RKString("GLN+HE21") ,"H"},
  {RKString("GLN+HE22") ,"H"},

  {RKString("GLU+C")    ,"C"},
  {RKString("GLU+CA")   ,"C"},
  {RKString("GLU+CB")   ,"C"},
  {RKString("GLU+CD")   ,"C"},
  {RKString("GLU+CG")   ,"C"},
  {RKString("GLU+N")    ,"N"},
  {RKString("GLU+O")    ,"O"},
  {RKString("GLU+OE1")  ,"O"},
  {RKString("GLU+OE2")  ,"O"},
  {RKString("GLU+OXT")  ,"O"},
  {RKString("GLU+H")    ,"H"},
  {RKString("GLU+HA")   ,"H"},
  {RKString("GLU+HB2")  ,"H"},
  {RKString("GLU+HB3")  ,"H"},
  {RKString("GLU+HG2")  ,"H"},
  {RKString("GLU+HG3")  ,"H"},

  {RKString("GLY+C")    ,"C"},
  {RKString("GLY+CA")   ,"C"},
  {RKString("GLY+N")    ,"N"},
  {RKString("GLY+O")    ,"O"},
  {RKString("GLY+OXT")  ,"O"},
  {RKString("GLY+H")    ,"H"},
  {RKString("GLY+HA")   ,"H"},
  {RKString("GLY+HA2")  ,"H"},
  {RKString("GLY+HA3")  ,"H"},
  {RKString("GLY+HB2")  ,"H"},
  {RKString("GLY+HB3")  ,"H"},
  {RKString("GLY+HG2")  ,"H"},
  {RKString("GLY+HG3")  ,"H"},

  {RKString("HIS+C")    ,"C"},
  {RKString("HIS+CA")   ,"C"},
  {RKString("HIS+CB")   ,"C"},
  {RKString("HIS+CD2")  ,"C"},
  {RKString("HIS+CE1")  ,"C"},
  {RKString("HIS+CG")   ,"C"},
  {RKString("HIS+N")    ,"N"},
  {RKString("HIS+ND1")  ,"N"},
  {RKString("HIS+NE2")  ,"N"},
  {RKString("HIS+O")    ,"O"},
  {RKString("HIS+OXT")  ,"O"},
  {RKString("HIS+H")    ,"H"},
  {RKString("HIS+HA")   ,"H"},
  {RKString("HIS+HB2")  ,"H"},
  {RKString("HIS+HB3")  ,"H"},
  {RKString("HIS+HD1")  ,"H"},
  {RKString("HIS+HD2")  ,"H"},
  {RKString("HIS+HE1")  ,"H"},

  {RKString("HOH+O")    ,"C"},
  {RKString("HOH+H")    ,"H"},

  {RKString("ILE+C")    ,"C"},
  {RKString("ILE+CA")   ,"C"},
  {RKString("ILE+CB")   ,"C"},
  {RKString("ILE+CD1")  ,"C"},
  {RKString("ILE+CG1")  ,"C"},
  {RKString("ILE+CG2")  ,"C"},
  {RKString("ILE+N")    ,"N"},
  {RKString("ILE+O")    ,"O"},
  {RKString("ILE+OXT")  ,"O"},
  {RKString("ILE+H")    ,"H"},
  {RKString("ILE+HA")   ,"H"},
  {RKString("ILE+HB")   ,"H"},
  {RKString("ILE+HG12") ,"H"},
  {RKString("ILE+HG13") ,"H"},
  {RKString("ILE+HG21") ,"H"},
  {RKString("ILE+HG22") ,"H"},
  {RKString("ILE+HG23") ,"H"},
  {RKString("ILE+HD11") ,"H"},
  {RKString("ILE+HD12") ,"H"},
  {RKString("ILE+HD13") ,"H"},

  {RKString("LEU+C")    ,"C"},
  {RKString("LEU+CA")   ,"C"},
  {RKString("LEU+CB")   ,"C"},
  {RKString("LEU+CD1")  ,"C"},
  {RKString("LEU+CD2")  ,"C"},
  {RKString("LEU+CG")   ,"C"},
  {RKString("LEU+N")    ,"N"},
  {RKString("LEU+O")    ,"O"},
  {RKString("LEU+H")    ,"H"},
  {RKString("LEU+HA")   ,"H"},
  {RKString("LEU+HB2")  ,"H"},
  {RKString("LEU+HB3")  ,"H"},
  {RKString("LEU+HD11") ,"H"},
  {RKString("LEU+HD12") ,"H"},
  {RKString("LEU+HD13") ,"H"},
  {RKString("LEU+HD21") ,"H"},
  {RKString("LEU+HD22") ,"H"},
  {RKString("LEU+HD23") ,"H"},
  {RKString("LEU+HG")   ,"H"},

  {RKString("LYS+C")    ,"C"},
  {RKString("LYS+CA")   ,"C"},
  {RKString("LYS+CB")   ,"C"},
  {RKString("LYS+CD")   ,"C"},
  {RKString("LYS+CE")   ,"C"},
  {RKString("LYS+CG")   ,"C"},
  {RKString("LYS+N")    ,"N"},
  {RKString("LYS+NZ")   ,"N"},
  {RKString("LYS+O")    ,"O"},
  {RKString("LYS+OXT")  ,"O"},
  {RKString("LYS+H")    ,"H"},
  {RKString("LYS+HA")   ,"H"},
  {RKString("LYS+HB2")  ,"H"},
  {RKString("LYS+HB3")  ,"H"},
  {RKString("LYS+HG2")  ,"H"},
  {RKString("LYS+HG3")  ,"H"},
  {RKString("LYS+HD2")  ,"H"},
  {RKString("LYS+HD3")  ,"H"},
  {RKString("LYS+HE2")  ,"H"},
  {RKString("LYS+HE3")  ,"H"},

  {RKString("MET+C")    ,"C"},
  {RKString("MET+CA")   ,"C"},
  {RKString("MET+CB")   ,"C"},
  {RKString("MET+CE")   ,"C"},
  {RKString("MET+CG")   ,"C"},
  {RKString("MET+N")    ,"N"},
  {RKString("MET+O")    ,"O"},
  {RKString("MET+SD")   ,"S"},
  {RKString("MET+OXT")  ,"O"},
  {RKString("MET+H")    ,"H"},

  {RKString("PHE+C")    ,"C"},
  {RKString("PHE+CA")   ,"C"},
  {RKString("PHE+CB")   ,"C"},
  {RKString("PHE+CD1")  ,"C"},
  {RKString("PHE+CD2")  ,"C"},
  {RKString("PHE+CE1")  ,"C"},
  {RKString("PHE+CE2")  ,"C"},
  {RKString("PHE+CG")   ,"C"},
  {RKString("PHE+CZ")   ,"C"},
  {RKString("PHE+N")    ,"N"},
  {RKString("PHE+O")    ,"O"},
  {RKString("PHE+OXT")  ,"O"},
  {RKString("PHE+H")    ,"H"},
  {RKString("PHE+HA")   ,"H"},
  {RKString("PHE+HB2")  ,"H"},
  {RKString("PHE+HB3")  ,"H"},
  {RKString("PHE+HD1")  ,"H"},
  {RKString("PHE+HD2")  ,"H"},
  {RKString("PHE+HE1")  ,"H"},
  {RKString("PHE+HE2")  ,"H"},
  {RKString("PHE+HZ")   ,"H"},

  {RKString("PRO+C")    ,"C"},
  {RKString("PRO+CA")   ,"C"},
  {RKString("PRO+CB")   ,"C"},
  {RKString("PRO+CD")   ,"C"},
  {RKString("PRO+CG")   ,"C"},
  {RKString("PRO+N")    ,"N"},
  {RKString("PRO+O")    ,"O"},
  {RKString("PRO+OXT")  ,"O"},
  {RKString("PRO+H")    ,"H"},
  {RKString("PRO+HA")   ,"H"},
  {RKString("PRO+HB2")  ,"H"},
  {RKString("PRO+HB3")  ,"H"},
  {RKString("PRO+HD2")  ,"H"},
  {RKString("PRO+HD3")  ,"H"},
  {RKString("PRO+HG2")  ,"H"},
  {RKString("PRO+HG3")  ,"H"},

  {RKString("SER+C")    ,"C"},
  {RKString("SER+CA")   ,"C"},
  {RKString("SER+CB")   ,"C"},
  {RKString("SER+N")    ,"N"},
  {RKString("SER+O")    ,"O"},
  {RKString("SER+OG")   ,"O"},
  {RKString("SER+OXT")  ,"O"},
  {RKString("SER+H")    ,"H"},
  {RKString("SER+HA")   ,"H"},
  {RKString("SER+HB2")  ,"H"},
  {RKString("SER+HB3")  ,"H"},

  {RKString("THR+C")    ,"C"},
  {RKString("THR+CA")   ,"C"},
  {RKString("THR+CB")   ,"C"},
  {RKString("THR+CG2")  ,"C"},
  {RKString("THR+N")    ,"N"},
  {RKString("THR+O")    ,"O"},
  {RKString("THR+OG1")  ,"O"},
  {RKString("THR+OXT")  ,"O"},
  {RKString("THR+H")    ,"H"},
  {RKString("THR+HA")   ,"H"},
  {RKString("THR+HB")   ,"H"},
  {RKString("THR+HG1")  ,"H"},
  {RKString("THR+HG21") ,"H"},
  {RKString("THR+HG22") ,"H"},
  {RKString("THR+HG23") ,"H"},
  {RKString("THR+HH2")  ,"H"},

  {RKString("TRP+C")    ,"C"},
  {RKString("TRP+CA")   ,"C"},
  {RKString("TRP+CB")   ,"C"},
  {RKString("TRP+CD1")  ,"C"},
  {RKString("TRP+CD2")  ,"C"},
  {RKString("TRP+CE2")  ,"C"},
  {RKString("TRP+CE3")  ,"C"},
  {RKString("TRP+CG")   ,"C"},
  {RKString("TRP+CH2")  ,"C"},
  {RKString("TRP+CZ2")  ,"C"},
  {RKString("TRP+CZ3")  ,"C"},
  {RKString("TRP+N")    ,"N"},
  {RKString("TRP+NE1")  ,"N"},
  {RKString("TRP+O")    ,"O"},
  {RKString("TRP+OXT")  ,"O"},
  {RKString("TRP+H")    ,"H"},
  {RKString("TRP+HA")   ,"H"},
  {RKString("TRP+HB2")  ,"H"},
  {RKString("TRP+HB3")  ,"H"},
  {RKString("TRP+HD1")  ,"H"},
  {RKString("TRP+HE1")  ,"H"},
  {RKString("TRP+HE3")  ,"H"},
  {RKString("TRP+HZ2")  ,"H"},
  {RKString("TRP+HZ3")  ,"H"},
  {RKString("TRP+HH2")  ,"H"},

  {RKString("TYR+C")    ,"C"},
  {RKString("TYR+CA")   ,"C"},
  {RKString("TYR+CB")   ,"C"},
  {RKString("TYR+CD1")  ,"C"},
  {RKString("TYR+CD2")  ,"C"},
  {RKString("TYR+CE1")  ,"C"},
  {RKString("TYR+CE2")  ,"C"},
  {RKString("TYR+CG")   ,"C"},
  {RKString("TYR+CZ")   ,"C"},
  {RKString("TYR+N")    ,"N"},
  {RKString("TYR+O")    ,"O"},
  {RKString("TYR+OH")   ,"O"},
  {RKString("TYR+OXT")  ,"O"},
  {RKString("TYR+H")    ,"H"},
  {RKString("TYR+HA")   ,"H"},
  {RKString("TYR+HB2")  ,"H"},
  {RKString("TYR+HB3")  ,"H"},
  {RKString("TYR+HD1")  ,"H"},
  {RKString("TYR+HD2")  ,"H"},
  {RKString("TYR+HE1")  ,"H"},
  {RKString("TYR+HE2")  ,"H"},

  {RKString("VAL+C")    ,"C"},
  {RKString("VAL+CA")   ,"C"},
  {RKString("VAL+CB")   ,"C"},
  {RKString("VAL+CG1")  ,"C"},
  {RKString("VAL+CG2")  ,"C"},
  {RKString("VAL+N")    ,"N"},
  {RKString("VAL+O")    ,"O"},
  {RKString("VAL+OXT")  ,"O"},
  {RKString("VAL+H")    ,"H"},
  {RKString("VAL+HA")   ,"H"},
  {RKString("VAL+HB")   ,"H"},
  {RKString("VAL+HG11") ,"H"},
  {RKString("VAL+HG12") ,"H"},
  {RKString("VAL+HG13") ,"H"},
  {RKString("VAL+HG21") ,"H"},
  {RKString("VAL+HG22") ,"H"},
  {RKString("VAL+HG23") ,"H"}
};

std::map<RKString, RKString> PredefinedElements::residueDefinitionsType =
{
  {RKString("ALA+C")    ,"C"},
  {RKString("ALA+CA")   ,"CH1E"},
  {RKString("ALA+CB")   ,"CH3E"},
  {RKString("ALA+N")    ,"NH1"},
  {RKString("ALA+O")    ,"O"},
  {RKString("ALA+OXT")  ,"O"},
  {RKString("ALA+H")    ,"H"},
  {RKString("ALA+HA")   ,"H"},
  {RKString("ALA+HB1")  ,"H"},
  {RKString("ALA+HB2")  ,"H"},
  {RKString("ALA+HB3")  ,"H"},

  {RKString("ARG+C")    ,"C"},
  {RKString("ARG+CA")   ,"CH1E"},
  {RKString("ARG+CB")   ,"CH2E"},
  {RKString("ARG+CD")   ,"CH2E"},
  {RKString("ARG+CG")   ,"CH2E"},
  {RKString("ARG+CZ")   ,"CH0"},
  {RKString("ARG+N")    ,"NH1"},
  {RKString("ARG+NE")   ,"NH1S"},
  {RKString("ARG+NH1")  ,"NC2"},
  {RKString("ARG+NH2")  ,"NC2"},
  {RKString("ARG+O")    ,"O"},
  {RKString("ARG+OXT")  ,"O"},
  {RKString("ARG+H")    ,"H"},
  {RKString("ARG+HA")   ,"H"},
  {RKString("ARG+HB2")  ,"H"},
  {RKString("ARG+HB3")  ,"H"},
  {RKString("ARG+HD2")  ,"H"},
  {RKString("ARG+HD3")  ,"H"},
  {RKString("ARG+HE")   ,"H"},
  {RKString("ARG+HG2")  ,"H"},
  {RKString("ARG+HG3")  ,"H"},
  {RKString("ARG+HH11") ,"H"},
  {RKString("ARG+HH12") ,"H"},
  {RKString("ARG+HH21") ,"H"},
  {RKString("ARG+HH22") ,"H"},

  {RKString("ASN+C")    ,"C"},
  {RKString("ASN+CA")   ,"CH1E"},
  {RKString("ASN+CB")   ,"CH2E"},
  {RKString("ASN+CG")   ,"CH0"},
  {RKString("ASN+N")    ,"NH1"},
  {RKString("ASN+ND2")  ,"NH2"},
  {RKString("ASN+O")    ,"O"},
  {RKString("ASN+OD1")  ,"OS"},
  {RKString("ASN+OXT")  ,"O"},
  {RKString("ASN+H")    ,"H"},
  {RKString("ASN+HA")   ,"H"},
  {RKString("ASN+HB2")  ,"H"},
  {RKString("ASN+HB3")  ,"H"},
  {RKString("ASN+HD21") ,"H"},
  {RKString("ASN+HD22") ,"H"},

  {RKString("ASP+C")    ,"C"},
  {RKString("ASP+CA")   ,"CH1E"},
  {RKString("ASP+CB")   ,"CH2E"},
  {RKString("ASP+CG")   ,"CH0"},
  {RKString("ASP+N")    ,"NH1"},
  {RKString("ASP+O")    ,"O"},
  {RKString("ASP+OD1")  ,"OC"},
  {RKString("ASP+OD2")  ,"OC"},
  {RKString("ASP+OXT")  ,"O"},
  {RKString("ASP+H")    ,"H"},
  {RKString("ASP+HA")   ,"H"},
  {RKString("ASP+HB2")  ,"H"},
  {RKString("ASP+HB3")  ,"H"},

  {RKString("CYS+C")    ,"C"},
  {RKString("CYS+CA")   ,"CH1E"},
  {RKString("CYS+CB")   ,"CH2E"},
  {RKString("CYS+N")    ,"NH1"},
  {RKString("CYS+O")    ,"O"},
  {RKString("CYS+SG")   ,"SH1E"},
  {RKString("CYS+OXT")  ,"O"},
  {RKString("CYS+H")    ,"H"},
  {RKString("CYS+HA")   ,"H"},
  {RKString("CYS+HB2")  ,"H"},
  {RKString("CYS+HB3")  ,"H"},

  {RKString("GLN+C")    ,"C"},
  {RKString("GLN+CA")   ,"CH1E"},
  {RKString("GLN+CB")   ,"CH2E"},
  {RKString("GLN+CD")   ,"CH0"},
  {RKString("GLN+CG")   ,"CH2E"},
  {RKString("GLN+N")    ,"NH1"},
  {RKString("GLN+NE2")  ,"NH2"},
  {RKString("GLN+O")    ,"O"},
  {RKString("GLN+OE1")  ,"OS"},
  {RKString("GLN+OXT")  ,"O"},
  {RKString("GLN+H")    ,"H"},
  {RKString("GLN+HA")   ,"H"},
  {RKString("GLN+HB2")  ,"H"},
  {RKString("GLN+HB3")  ,"H"},
  {RKString("GLN+HG2")  ,"H"},
  {RKString("GLN+HG3")  ,"H"},
  {RKString("GLN+HE21") ,"H"},
  {RKString("GLN+HE22") ,"H"},

  {RKString("GLU+C")    ,"C"},
  {RKString("GLU+CA")   ,"CH1E"},
  {RKString("GLU+CB")   ,"CH2E"},
  {RKString("GLU+CD")   ,"CH0"},
  {RKString("GLU+CG")   ,"CH2E"},
  {RKString("GLU+N")    ,"NH1"},
  {RKString("GLU+O")    ,"O"},
  {RKString("GLU+OE1")  ,"OC"},
  {RKString("GLU+OE2")  ,"OC"},
  {RKString("GLU+OXT")  ,"O"},
  {RKString("GLU+H")    ,"H"},
  {RKString("GLU+HA")   ,"H"},
  {RKString("GLU+HB2")  ,"H"},
  {RKString("GLU+HB3")  ,"H"},
  {RKString("GLU+HG2")  ,"H"},
  {RKString("GLU+HG3")  ,"H"},

  {RKString("GLY+C")    ,"C"},
  {RKString("GLY+CA")   ,"CH2G"},
  {RKString("GLY+N")    ,"NH1"},
  {RKString("GLY+O")    ,"O"},
  {RKString("GLY+OXT")  ,"O"},
  {RKString("GLY+H")    ,"H"},
  {RKString("GLY+HA")   ,"H"},
  {RKString("GLY+HA2")  ,"H"},
  {RKString("GLY+HA3")  ,"H"},
  {RKString("GLY+HB2")  ,"H"},
  {RKString("GLY+HB3")  ,"H"},
  {RKString("GLY+HG2")  ,"H"},
  {RKString("GLY+HG3")  ,"H"},

  {RKString("HIS+C")    ,"C"},
  {RKString("HIS+CA")   ,"CH1E"},
  {RKString("HIS+CB")   ,"CH2E"},
  {RKString("HIS+CD2")  ,"CR1H"},
  {RKString("HIS+CE1")  ,"CRHH"},
  {RKString("HIS+CG")   ,"C5"},
  {RKString("HIS+N")    ,"NH1"},
  {RKString("HIS+ND1")  ,"NH1S"},
  {RKString("HIS+NE2")  ,"NH1S"},
  {RKString("HIS+O")    ,"O"},
  {RKString("HIS+OXT")  ,"O"},
  {RKString("HIS+H")    ,"H"},
  {RKString("HIS+HA")   ,"H"},
  {RKString("HIS+HB2")  ,"H"},
  {RKString("HIS+HB3")  ,"H"},
  {RKString("HIS+HD1")  ,"H"},
  {RKString("HIS+HD2")  ,"H"},
  {RKString("HIS+HE1")  ,"H"},

  {RKString("HOH+O")    ,"HOH"},
  {RKString("HOH+H")    ,"HOH"},

  {RKString("ILE+C")    ,"C"},
  {RKString("ILE+CA")   ,"CH1E"},
  {RKString("ILE+CB")   ,"CH1S"},
  {RKString("ILE+CD1")  ,"CH3E"},
  {RKString("ILE+CG1")  ,"CH2E"},
  {RKString("ILE+CG2")  ,"CH3E"},
  {RKString("ILE+N")    ,"NH1"},
  {RKString("ILE+O")    ,"O"},
  {RKString("ILE+OXT")  ,"O"},
  {RKString("ILE+H")    ,"H"},
  {RKString("ILE+HA")   ,"H"},
  {RKString("ILE+HB")   ,"H"},
  {RKString("ILE+HG12") ,"H"},
  {RKString("ILE+HG13") ,"H"},
  {RKString("ILE+HG21") ,"H"},
  {RKString("ILE+HG22") ,"H"},
  {RKString("ILE+HG23") ,"H"},
  {RKString("ILE+HD11") ,"H"},
  {RKString("ILE+HD12") ,"H"},
  {RKString("ILE+HD13") ,"H"},

  {RKString("LEU+C")    ,"C"},
  {RKString("LEU+CA")   ,"CH1E"},
  {RKString("LEU+CB")   ,"CH2E"},
  {RKString("LEU+CD1")  ,"CH3E"},
  {RKString("LEU+CD2")  ,"CH3E"},
  {RKString("LEU+CG")   ,"CH1S"},
  {RKString("LEU+N")    ,"NH1"},
  {RKString("LEU+O")    ,"O"},
  {RKString("LEU+H")    ,"H"},
  {RKString("LEU+HA")   ,"H"},
  {RKString("LEU+HB2")  ,"H"},
  {RKString("LEU+HB3")  ,"H"},
  {RKString("LEU+HD11") ,"H"},
  {RKString("LEU+HD12") ,"H"},
  {RKString("LEU+HD13") ,"H"},
  {RKString("LEU+HD21") ,"H"},
  {RKString("LEU+HD22") ,"H"},
  {RKString("LEU+HD23") ,"H"},
  {RKString("LEU+HG")   ,"H"},

  {RKString("LYS+C")    ,"C"},
  {RKString("LYS+CA")   ,"CH1E"},
  {RKString("LYS+CB")   ,"CH2E"},
  {RKString("LYS+CD")   ,"CH2E"},
  {RKString("LYS+CE")   ,"CH2E"},
  {RKString("LYS+CG")   ,"CH2E"},
  {RKString("LYS+N")    ,"NH1"},
  {RKString("LYS+NZ")   ,"NH3"},
  {RKString("LYS+O")    ,"O"},
  {RKString("LYS+OXT")  ,"O"},
  {RKString("LYS+H")    ,"H"},
  {RKString("LYS+HA")   ,"H"},
  {RKString("LYS+HB2")  ,"H"},
  {RKString("LYS+HB3")  ,"H"},
  {RKString("LYS+HG2")  ,"H"},
  {RKString("LYS+HG3")  ,"H"},
  {RKString("LYS+HD2")  ,"H"},
  {RKString("LYS+HD3")  ,"H"},
  {RKString("LYS+HE2")  ,"H"},
  {RKString("LYS+HE3")  ,"H"},

  {RKString("MET+C")    ,"C"},
  {RKString("MET+CA")   ,"CH1E"},
  {RKString("MET+CB")   ,"CH2E"},
  {RKString("MET+CE")   ,"CH3E"},
  {RKString("MET+CG")   ,"CH2E"},
  {RKString("MET+N")    ,"NH1"},
  {RKString("MET+O")    ,"O"},
  {RKString("MET+SD")   ,"SM"},
  {RKString("MET+OXT")  ,"O"},
  {RKString("MET+H")    ,"H"},

  {RKString("PHE+C")    ,"C"},
  {RKString("PHE+CA")   ,"CH1E"},
  {RKString("PHE+CB")   ,"CH2E"},
  {RKString("PHE+CD1")  ,"CR1E"},
  {RKString("PHE+CD2")  ,"CR1E"},
  {RKString("PHE+CE1")  ,"CR1E"},
  {RKString("PHE+CE2")  ,"CR1E"},
  {RKString("PHE+CG")   ,"CF"},
  {RKString("PHE+CZ")   ,"CR1E"},
  {RKString("PHE+N")    ,"NH1"},
  {RKString("PHE+O")    ,"O"},
  {RKString("PHE+OXT")  ,"O"},
  {RKString("PHE+H")    ,"H"},
  {RKString("PHE+HA")   ,"H"},
  {RKString("PHE+HB2")  ,"H"},
  {RKString("PHE+HB3")  ,"H"},
  {RKString("PHE+HD1")  ,"H"},
  {RKString("PHE+HD2")  ,"H"},
  {RKString("PHE+HE1")  ,"H"},
  {RKString("PHE+HE2")  ,"H"},
  {RKString("PHE+HZ")   ,"H"},

  {RKString("PRO+C")    ,"C"},
  {RKString("PRO+CA")   ,"CH1E"},
  {RKString("PRO+CB")   ,"CH2E"},
  {RKString("PRO+CD")   ,"CH2P"},
  {RKString("PRO+CG")   ,"CH2P"},
  {RKString("PRO+N")    ,"N"},
  {RKString("PRO+O")    ,"O"},
  {RKString("PRO+OXT")  ,"O"},
  {RKString("PRO+H")    ,"H"},
  {RKString("PRO+HA")   ,"H"},
  {RKString("PRO+HB2")  ,"H"},
  {RKString("PRO+HB3")  ,"H"},
  {RKString("PRO+HD2")  ,"H"},
  {RKString("PRO+HD3")  ,"H"},
  {RKString("PRO+HG2")  ,"H"},
  {RKString("PRO+HG3")  ,"H"},

  {RKString("SER+C")    ,"C"},
  {RKString("SER+CA")   ,"CH1E"},
  {RKString("SER+CB")   ,"CH2E"},
  {RKString("SER+N")    ,"NH1"},
  {RKString("SER+O")    ,"O"},
  {RKString("SER+OG")   ,"OH1"},
  {RKString("SER+OXT")  ,"O"},
  {RKString("SER+H")    ,"H"},
  {RKString("SER+HA")   ,"H"},
  {RKString("SER+HB2")  ,"H"},
  {RKString("SER+HB3")  ,"H"},

  {RKString("THR+C")    ,"C"},
  {RKString("THR+CA")   ,"CH1E"},
  {RKString("THR+CB")   ,"CH1S"},
  {RKString("THR+CG2")  ,"CH3E"},
  {RKString("THR+N")    ,"NH1"},
  {RKString("THR+O")    ,"O"},
  {RKString("THR+OG1")  ,"OH1"},
  {RKString("THR+OXT")  ,"O"},
  {RKString("THR+H")    ,"H"},
  {RKString("THR+HA")   ,"H"},
  {RKString("THR+HB")   ,"H"},
  {RKString("THR+HG1")  ,"H"},
  {RKString("THR+HG21") ,"H"},
  {RKString("THR+HG22") ,"H"},
  {RKString("THR+HG23") ,"H"},
  {RKString("THR+HH2")  ,"H"},

  {RKString("TRP+C")    ,"C"},
  {RKString("TRP+CA")   ,"CH1E"},
  {RKString("TRP+CB")   ,"CH2E"},
  {RKString("TRP+CD1")  ,"CR1E"},
  {RKString("TRP+CD2")  ,"CW"},
  {RKString("TRP+CE2")  ,"CW"},
  {RKString("TRP+CE3")  ,"CR1E"},
  {RKString("TRP+CG")   ,"C5W"},
  {RKString("TRP+CH2")  ,"CR1W"},
  {RKString("TRP+CZ2")  ,"CR1W"},
  {RKString("TRP+CZ3")  ,"CR1E"},
  {RKString("TRP+N")    ,"NH1"},
  {RKString("TRP+NE1")  ,"NH1S"},
  {RKString("TRP+O")    ,"O"},
  {RKString("TRP+OXT")  ,"O"},
  {RKString("TRP+H")    ,"H"},
  {RKString("TRP+HA")   ,"H"},
  {RKString("TRP+HB2")  ,"H"},
  {RKString("TRP+HB3")  ,"H"},
  {RKString("TRP+HD1")  ,"H"},
  {RKString("TRP+HE1")  ,"H"},
  {RKString("TRP+HE3")  ,"H"},
  {RKString("TRP+HZ2")  ,"H"},
  {RKString("TRP+HZ3")  ,"H"},
  {RKString("TRP+HH2")  ,"H"},

  {RKString("TYR+C")    ,"C"},
  {RKString("TYR+CA")   ,"CH1E"},
  {RKString("TYR+CB")   ,"CH2E"},
  {RKString("TYR+CD1")  ,"CR1E"},
  {RKString("TYR+CD2")  ,"CR1E"},
  {RKString("TYR+CE1")  ,"CR1E"},
  {RKString("TYR+CE2")  ,"CR1E"},
  {RKString("TYR+CG")   ,"CY"},
  {RKString("TYR+CZ")   ,"CY2"},
  {RKString("TYR+N")    ,"NH1"},
  {RKString("TYR+O")    ,"O"},
  {RKString("TYR+OH")   ,"OH1"},
  {RKString("TYR+OXT")  ,"O"},
  {RKString("TYR+H")    ,"H"},
  {RKString("TYR+HA")   ,"H"},
  {RKString("TYR+HB2")  ,"H"},
  {RKString("TYR+HB3")  ,"H"},
  {RKString("TYR+HD1")  ,"H"},
  {RKString("TYR+HD2")  ,"H"},
  {RKString("TYR+HE1")  ,"H"},
  {RKString("TYR+HE2")  ,"H"},

  {RKString("VAL+C")    ,"C"},
  {RKString("VAL+CA")   ,"CH1E"},
  {RKString("VAL+CB")   ,"CH1S"},
  {RKString("VAL+CG1")  ,"CH3E"},
  {RKString("VAL+CG2")  ,"CH3E"},
  {RKString("VAL+N")    ,"NH1"},
  {RKString("VAL+O")    ,"O"},
  {RKString("VAL+OXT")  ,"O"},
  {RKString("VAL+H")    ,"H"},
  {RKString("VAL+HA")   ,"H"},
  {RKString("VAL+HB")   ,"H"},
  {RKString("VAL+HG11") ,"H"},
  {RKString("VAL+HG12") ,"H"},
  {RKString("VAL+HG13") ,"H"},
  {RKString("VAL+HG21") ,"H"},
  {RKString("VAL+HG22") ,"H"},
  {RKString("VAL+HG23") ,"H"}
};

std::map<RKString, std::vector<RKString>> PredefinedElements::residueDefinitionsBondedAtoms =
{
  {RKString("ALA+C")    ,{"CA","O"}},
  {RKString("ALA+CA")   ,{"N","CB","C"}},
  {RKString("ALA+CB")   ,{"CA"}},
  {RKString("ALA+N")    ,{"-C","CA"}},
  {RKString("ALA+O")    ,{"C"}},
  {RKString("ALA+OXT")  ,{"C"}},
  {RKString("ALA+H")    ,{}},
  {RKString("ALA+HA")   ,{}},
  {RKString("ALA+HB1")  ,{}},
  {RKString("ALA+HB2")  ,{}},
  {RKString("ALA+HB3")  ,{}},

  {RKString("ARG+C")    ,{"CA","O"}},
  {RKString("ARG+CA")   ,{"N ","CB ","C"}},
  {RKString("ARG+CB")   ,{"CA","CG"}},
  {RKString("ARG+CD")   ,{"CG","NE"}},
  {RKString("ARG+CG")   ,{"CB","CD"}},
  {RKString("ARG+CZ")   ,{"NE"," NH1","NH2"}},
  {RKString("ARG+N")    ,{"-C","CA"}},
  {RKString("ARG+NE")   ,{"CD","CZ"}},
  {RKString("ARG+NH1")  ,{"CZ"}},
  {RKString("ARG+NH2")  ,{"CZ"}},
  {RKString("ARG+O")    ,{"C"}},
  {RKString("ARG+OXT")  ,{"C"}},
  {RKString("ARG+H")    ,{}},
  {RKString("ARG+HA")   ,{}},
  {RKString("ARG+HB2")  ,{}},
  {RKString("ARG+HB3")  ,{}},
  {RKString("ARG+HD2")  ,{}},
  {RKString("ARG+HD3")  ,{}},
  {RKString("ARG+HE")   ,{}},
  {RKString("ARG+HG2")  ,{}},
  {RKString("ARG+HG3")  ,{}},
  {RKString("ARG+HH11") ,{}},
  {RKString("ARG+HH12") ,{}},
  {RKString("ARG+HH21") ,{}},
  {RKString("ARG+HH22") ,{}},

  {RKString("ASN+C")    ,{"CA","O"}},
  {RKString("ASN+CA")   ,{"N","CB","C"}},
  {RKString("ASN+CB")   ,{"CA","CG"}},
  {RKString("ASN+CG")   ,{"CB","OD1","ND2"}},
  {RKString("ASN+N")    ,{"-C","CA"}},
  {RKString("ASN+ND2")  ,{"CG"}},
  {RKString("ASN+O")    ,{"C"}},
  {RKString("ASN+OD1")  ,{"CG"}},
  {RKString("ASN+OXT")  ,{"C"}},
  {RKString("ASN+H")    ,{}},
  {RKString("ASN+HA")   ,{}},
  {RKString("ASN+HB2")  ,{}},
  {RKString("ASN+HB3")  ,{}},
  {RKString("ASN+HD21") ,{}},
  {RKString("ASN+HD22") ,{}},

  {RKString("ASP+C")    ,{"CA","O"}},
  {RKString("ASP+CA")   ,{"N ","CB","C"}},
  {RKString("ASP+CB")   ,{"CA ","CG"}},
  {RKString("ASP+CG")   ,{"CB ","OD1","OD2"}},
  {RKString("ASP+N")    ,{"-C ","CA"}},
  {RKString("ASP+O")    ,{"C"}},
  {RKString("ASP+OD1")  ,{"CG"}},
  {RKString("ASP+OD2")  ,{"CG"}},
  {RKString("ASP+OXT")  ,{"C"}},
  {RKString("ASP+H")    ,{}},
  {RKString("ASP+HA")   ,{}},
  {RKString("ASP+HB2")  ,{}},
  {RKString("ASP+HB3")  ,{}},

  {RKString("CYS+C")    ,{"CA","O"}},
  {RKString("CYS+CA")   ,{"N","CB ","C"}},
  {RKString("CYS+CB")   ,{"CA","SG"}},
  {RKString("CYS+N")    ,{"-C","CA"}},
  {RKString("CYS+O")    ,{"C"}},
  {RKString("CYS+SG")   ,{"CB"}},
  {RKString("CYS+OXT")  ,{"C"}},
  {RKString("CYS+H")    ,{}},
  {RKString("CYS+HA")   ,{}},
  {RKString("CYS+HB2")  ,{}},
  {RKString("CYS+HB3")  ,{}},

  {RKString("GLN+C")    ,{"CA","O"}},
  {RKString("GLN+CA")   ,{"N","CB","C"}},
  {RKString("GLN+CB")   ,{"CA ","CG"}},
  {RKString("GLN+CD")   ,{"CG","NE2","OE1"}},
  {RKString("GLN+CG")   ,{"CB","CD"}},
  {RKString("GLN+N")    ,{"-C ","CA"}},
  {RKString("GLN+NE2")  ,{"CD"}},
  {RKString("GLN+O")    ,{"C"}},
  {RKString("GLN+OE1")  ,{"CD"}},
  {RKString("GLN+OXT")  ,{"C"}},
  {RKString("GLN+H")    ,{}},
  {RKString("GLN+HA")   ,{}},
  {RKString("GLN+HB2")  ,{}},
  {RKString("GLN+HB3")  ,{}},
  {RKString("GLN+HG2")  ,{}},
  {RKString("GLN+HG3")  ,{}},
  {RKString("GLN+HE21") ,{}},
  {RKString("GLN+HE22") ,{}},

  {RKString("GLU+C")    ,{"CA","O"}},
  {RKString("GLU+CA")   ,{"N","CB","C"}},
  {RKString("GLU+CB")   ,{"CA","CG"}},
  {RKString("GLU+CD")   ,{"CG","OE1 ","OE2"}},
  {RKString("GLU+CG")   ,{"CB ","CD"}},
  {RKString("GLU+N")    ,{"-C","CA"}},
  {RKString("GLU+O")    ,{"C"}},
  {RKString("GLU+OE1")  ,{"CD"}},
  {RKString("GLU+OE2")  ,{"CD"}},
  {RKString("GLU+OXT")  ,{"C"}},
  {RKString("GLU+H")    ,{}},
  {RKString("GLU+HA")   ,{}},
  {RKString("GLU+HB2")  ,{}},
  {RKString("GLU+HB3")  ,{}},
  {RKString("GLU+HG2")  ,{}},
  {RKString("GLU+HG3")  ,{}},

  {RKString("GLY+C")    ,{"CA","O"}},
  {RKString("GLY+CA")   ,{"N","C"}},
  {RKString("GLY+N")    ,{"-C","CA"}},
  {RKString("GLY+O")    ,{"C"}},
  {RKString("GLY+OXT")  ,{"C"}},
  {RKString("GLY+H")    ,{}},
  {RKString("GLY+HA")   ,{}},
  {RKString("GLY+HA2")  ,{}},
  {RKString("GLY+HA3")  ,{}},
  {RKString("GLY+HB2")  ,{}},
  {RKString("GLY+HB3")  ,{}},
  {RKString("GLY+HG2")  ,{}},
  {RKString("GLY+HG3")  ,{}},

  {RKString("HIS+C")    ,{"CA","O"}},
  {RKString("HIS+CA")   ,{"N","CB","C"}},
  {RKString("HIS+CB")   ,{"CA","CG"}},
  {RKString("HIS+CD2")  ,{"CG ","NE2"}},
  {RKString("HIS+CE1")  ,{"ND1","NE2"}},
  {RKString("HIS+CG")   ,{"CB","CD2","ND1"}},
  {RKString("HIS+N")    ,{"-C","CA"}},
  {RKString("HIS+ND1")  ,{"CG ","CE1"}},
  {RKString("HIS+NE2")  ,{"CD2","CE1"}},
  {RKString("HIS+O")    ,{"C"}},
  {RKString("HIS+OXT")  ,{"C"}},
  {RKString("HIS+H")    ,{}},
  {RKString("HIS+HA")   ,{}},
  {RKString("HIS+HB2")  ,{}},
  {RKString("HIS+HB3")  ,{}},
  {RKString("HIS+HD1")  ,{}},
  {RKString("HIS+HD2")  ,{}},
  {RKString("HIS+HE1")  ,{}},

  {RKString("HOH+O")    ,{}},
  {RKString("HOH+H")    ,{}},

  {RKString("ILE+C")    ,{"CA","O"}},
  {RKString("ILE+CA")   ,{"N ","CB ","C"}},
  {RKString("ILE+CB")   ,{"CA","CG1","CG2"}},
  {RKString("ILE+CD1")  ,{"CG1"}},
  {RKString("ILE+CG1")  ,{"CB ","CD1"}},
  {RKString("ILE+CG2")  ,{"CB"}},
  {RKString("ILE+N")    ,{"-C","CA"}},
  {RKString("ILE+O")    ,{"C"}},
  {RKString("ILE+OXT")  ,{"C"}},
  {RKString("ILE+H")    ,{}},
  {RKString("ILE+HA")   ,{}},
  {RKString("ILE+HB")   ,{}},
  {RKString("ILE+HG12") ,{}},
  {RKString("ILE+HG13") ,{}},
  {RKString("ILE+HG21") ,{}},
  {RKString("ILE+HG22") ,{}},
  {RKString("ILE+HG23") ,{}},
  {RKString("ILE+HD11") ,{}},
  {RKString("ILE+HD12") ,{}},
  {RKString("ILE+HD13") ,{}},

  {RKString("LEU+C")    ,{"CA","O"}},
  {RKString("LEU+CA")   ,{"N ","CB","C"}},
  {RKString("LEU+CB")   ,{"CA ","CG"}},
  {RKString("LEU+CD1")  ,{"CG"}},
  {RKString("LEU+CD2")  ,{"CG"}},
  {RKString("LEU+CG")   ,{"CB ","CD1","CD2"}},
  {RKString("LEU+N")    ,{"-C ","CA"}},
  {RKString("LEU+O")    ,{"C"}},
  {RKString("LEU+H")    ,{}},
  {RKString("LEU+HA")   ,{}},
  {RKString("LEU+HB2")  ,{}},
  {RKString("LEU+HB3")  ,{}},
  {RKString("LEU+HD11") ,{}},
  {RKString("LEU+HD12") ,{}},
  {RKString("LEU+HD13") ,{}},
  {RKString("LEU+HD21") ,{}},
  {RKString("LEU+HD22") ,{}},
  {RKString("LEU+HD23") ,{}},
  {RKString("LEU+HG")   ,{}},

  {RKString("LYS+C")    ,{"CA ","O"}},
  {RKString("LYS+CA")   ,{"N ","CB","C"}},
  {RKString("LYS+CB")   ,{"CA ","CG"}},
  {RKString("LYS+CD")   ,{"CG ","CE"}},
  {RKString("LYS+CE")   ,{"CD ","NZ"}},
  {RKString("LYS+CG")   ,{"CB ","CD"}},
  {RKString("LYS+N")    ,{"-C  ","CA"}},
  {RKString("LYS+NZ")   ,{"CE"}},
  {RKString("LYS+O")    ,{"C"}},
  {RKString("LYS+OXT")  ,{"C"}},
  {RKString("LYS+H")    ,{}},
  {RKString("LYS+HA")   ,{}},
  {RKString("LYS+HB2")  ,{}},
  {RKString("LYS+HB3")  ,{}},
  {RKString("LYS+HG2")  ,{}},
  {RKString("LYS+HG3")  ,{}},
  {RKString("LYS+HD2")  ,{}},
  {RKString("LYS+HD3")  ,{}},
  {RKString("LYS+HE2")  ,{}},
  {RKString("LYS+HE3")  ,{}},

  {RKString("MET+C")    ,{"CA ","O"}},
  {RKString("MET+CA")   ,{"N","CB","C"}},
  {RKString("MET+CB")   ,{"CA ","CG"}},
  {RKString("MET+CE")   ,{"SD"}},
  {RKString("MET+CG")   ,{"CB ","SD"}},
  {RKString("MET+N")    ,{"-C","CA"}},
  {RKString("MET+O")    ,{"C"}},
  {RKString("MET+SD")   ,{"CG ","CE"}},
  {RKString("MET+OXT")  ,{"C"}},
  {RKString("MET+H")    ,{}},

  {RKString("PHE+C")    ,{"CA","O"}},
  {RKString("PHE+CA")   ,{"N","CB","C"}},
  {RKString("PHE+CB")   ,{"CA","CG"}},
  {RKString("PHE+CD1")  ,{"CG ","CE1"}},
  {RKString("PHE+CD2")  ,{"CG ","CE2"}},
  {RKString("PHE+CE1")  ,{"CD1","CZ"}},
  {RKString("PHE+CE2")  ,{"CD2 ","CZ"}},
  {RKString("PHE+CG")   ,{"CB ","CD1","CD2"}},
  {RKString("PHE+CZ")   ,{"CE1","CE2"}},
  {RKString("PHE+N")    ,{"-C ","CA"}},
  {RKString("PHE+O")    ,{"C"}},
  {RKString("PHE+OXT")  ,{"C"}},
  {RKString("PHE+H")    ,{}},
  {RKString("PHE+HA")   ,{}},
  {RKString("PHE+HB2")  ,{}},
  {RKString("PHE+HB3")  ,{}},
  {RKString("PHE+HD1")  ,{}},
  {RKString("PHE+HD2")  ,{}},
  {RKString("PHE+HE1")  ,{}},
  {RKString("PHE+HE2")  ,{}},
  {RKString("PHE+HZ")   ,{}},

  {RKString("PRO+C")    ,{"CA","O"}},
  {RKString("PRO+CA")   ,{"N","CB","C"}},
  {RKString("PRO+CB")   ,{"CA","CG"}},
  {RKString("PRO+CD")   ,{"N","CG"}},
  {RKString("PRO+CG")   ,{"CB","CD"}},
  {RKString("PRO+N")    ,{"-C","CA","CD"}},
  {RKString("PRO+O")    ,{"C"}},
  {RKString("PRO+OXT")  ,{"C"}},
  {RKString("PRO+H")    ,{}},
  {RKString("PRO+HA")   ,{}},
  {RKString("PRO+HB2")  ,{}},
  {RKString("PRO+HB3")  ,{}},
  {RKString("PRO+HD2")  ,{}},
  {RKString("PRO+HD3")  ,{}},
  {RKString("PRO+HG2")  ,{}},
  {RKString("PRO+HG3")  ,{}},

  {RKString("SER+C")    ,{"CA","O"}},
  {RKString("SER+CA")   ,{"N","CB","C"}},
  {RKString("SER+CB")   ,{"CA","OG"}},
  {RKString("SER+N")    ,{"-C","CA"}},
  {RKString("SER+O")    ,{"C"}},
  {RKString("SER+OG")   ,{"CB"}},
  {RKString("SER+OXT")  ,{"C"}},
  {RKString("SER+H")    ,{}},
  {RKString("SER+HA")   ,{}},
  {RKString("SER+HB2")  ,{}},
  {RKString("SER+HB3")  ,{}},

  {RKString("THR+C")    ,{"CA","O"}},
  {RKString("THR+CA")   ,{"N","CB","C"}},
  {RKString("THR+CB")   ,{"CA","CG2","OG1"}},
  {RKString("THR+CG2")  ,{"CB"}},
  {RKString("THR+N")    ,{"-C","CA"}},
  {RKString("THR+O")    ,{"C"}},
  {RKString("THR+OG1")  ,{"CB"}},
  {RKString("THR+OXT")  ,{"C"}},
  {RKString("THR+H")    ,{}},
  {RKString("THR+HA")   ,{}},
  {RKString("THR+HB")   ,{}},
  {RKString("THR+HG1")  ,{}},
  {RKString("THR+HG21") ,{}},
  {RKString("THR+HG22") ,{}},
  {RKString("THR+HG23") ,{}},
  {RKString("THR+HH2")  ,{}},

  {RKString("TRP+C")    ,{"CA","O"}},
  {RKString("TRP+CA")   ,{"N ","CB","C"}},
  {RKString("TRP+CB")   ,{"CA","CG"}},
  {RKString("TRP+CD1")  ,{"CG ","NE1"}},
  {RKString("TRP+CD2")  ,{"CG "," CE2","CE3"}},
  {RKString("TRP+CE2")  ,{"CD2 ","CZ2","NE1"}},
  {RKString("TRP+CE3")  ,{"CD2","CZ3"}},
  {RKString("TRP+CG")   ,{"CB ","CD1","CD2"}},
  {RKString("TRP+CH2")  ,{"CZ2","CZ3"}},
  {RKString("TRP+CZ2")  ,{"CE2","CH2"}},
  {RKString("TRP+CZ3")  ,{"CE3","CH2"}},
  {RKString("TRP+N")    ,{"-C","CA"}},
  {RKString("TRP+NE1")  ,{"CD1 ","CE2"}},
  {RKString("TRP+O")    ,{"C"}},
  {RKString("TRP+OXT")  ,{"C"}},
  {RKString("TRP+H")    ,{}},
  {RKString("TRP+HA")   ,{}},
  {RKString("TRP+HB2")  ,{}},
  {RKString("TRP+HB3")  ,{}},
  {RKString("TRP+HD1")  ,{}},
  {RKString("TRP+HE1")  ,{}},
  {RKString("TRP+HE3")  ,{}},
  {RKString("TRP+HZ2")  ,{}},
  {RKString("TRP+HZ3")  ,{}},
  {RKString("TRP+HH2")  ,{}},

  {RKString("TYR+C")    ,{"CA","O"}},
  {RKString("TYR+CA")   ,{"N","CB","C"}},
  {RKString("TYR+CB")   ,{"CA","CG"}},
  {RKString("TYR+CD1")  ,{"CG","CE1"}},
  {RKString("TYR+CD2")  ,{"CG","CE2"}},
  {RKString("TYR+CE1")  ,{"CD1","CZ"}},
  {RKString("TYR+CE2")  ,{"CD2","CZ"}},
  {RKString("TYR+CG")   ,{"CB","CD1","CD2"}},
  {RKString("TYR+CZ")   ,{"CE1","CE2","OH"}},
  {RKString("TYR+N")    ,{"-C","CA"}},
  {RKString("TYR+O")    ,{"C"}},
  {RKString("TYR+OH")   ,{"CZ"}},
  {RKString("TYR+OXT")  ,{"C"}},
  {RKString("TYR+H")    ,{}},
  {RKString("TYR+HA")   ,{}},
  {RKString("TYR+HB2")  ,{}},
  {RKString("TYR+HB3")  ,{}},
  {RKString("TYR+HD1")  ,{}},
  {RKString("TYR+HD2")  ,{}},
  {RKString("TYR+HE1")  ,{}},
  {RKString("TYR+HE2")  ,{}},

  {RKString("VAL+C")    ,{"CA","O"}},
  {RKString("VAL+CA")   ,{"N","CB","C"}},
  {RKString("VAL+CB")   ,{"CA","CG1","CG2"}},
  {RKString("VAL+CG1")  ,{"CB"}},
  {RKString("VAL+CG2")  ,{"CB"}},
  {RKString("VAL+N")    ,{"-C","CA"}},
  {RKString("VAL+O")    ,{"C"}},
  {RKString("VAL+OXT")  ,{"C"}},
  {RKString("VAL+H")    ,{}},
  {RKString("VAL+HA")   ,{}},
  {RKString("VAL+HB")   ,{}},
  {RKString("VAL+HG11") ,{}},
  {RKString("VAL+HG12") ,{}},
  {RKString("VAL+HG13") ,{}},
  {RKString("VAL+HG21") ,{}},
  {RKString("VAL+HG22") ,{}},
  {RKString("VAL+HG23") ,{}}
};

std::optional<SKBackboneAtomRole> PredefinedElements::backboneAtomRole(const RKString &residueName, const RKString &atomName)
{
  const RKString key = residueName.trimmed().toUpper() + "+" + atomName.trimmed().toUpper();
  const auto typeIterator = residueDefinitionsType.find(key);
  if (typeIterator == residueDefinitionsType.end())
  {
    return std::nullopt;
  }
  return backboneAtomRoleForType(typeIterator->second);
}

std::optional<SKBackboneAtomRole> PredefinedElements::backboneAtomRoleForType(const RKString &type)
{
  const RKString trimmedType = type.trimmed();
  if (trimmedType == "NH1")
  {
    return SKBackboneAtomRole::nitrogen;
  }
  if (trimmedType == "CH1E" || trimmedType == "CH2G")
  {
    return SKBackboneAtomRole::alphaCarbon;
  }
  if (trimmedType == "C")
  {
    return SKBackboneAtomRole::carbonylCarbon;
  }
  if (trimmedType == "O")
  {
    return SKBackboneAtomRole::carbonylOxygen;
  }
  return std::nullopt;
}

bool PredefinedElements::isBackboneAtomType(const RKString &type)
{
  return backboneAtomRoleForType(type).has_value();
}
