/********************************************************************************************************************
    iRASPA: GPU-accelated visualisation software for materials scientists
    Copyright (c) 2016-2021 David Dubbeldam, Sofia Calero, Thijs J.H. Vlugt.
    D.Dubbeldam@uva.nl            https://www.uva.nl/en/profile/d/u/d.dubbeldam/d.dubbeldam.html
    S.Calero@tue.nl               https://www.tue.nl/en/research/researchers/sofia-calero/
    t.j.h.vlugt@tudelft.nl        http://homepage.tudelft.nl/v9k6y

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ********************************************************************************************************************/

#include <cmath>
#include "rkstring.h"
#include <cmath>
#include "skelement.h"
#include "skpdbwriter.h"

SKPDBWriter::SKPDBWriter(RKString displayName, SKSpaceGroup &spacegroup, std::shared_ptr<SKCell> cell, double3 origin, std::vector<std::shared_ptr<SKAsymmetricAtom>> atoms):
   _displayName(displayName), _spacegroup(spacegroup), _cell(cell), _origin(origin), _atoms(atoms)
{
}

RKString SKPDBWriter::string()
{
  RKString outputString = "COMPND    " + _displayName + "\n" + "AUTHOR    GENERATED BY IRASPA\n";

  if(_cell)
  {
    RKString spaceGroupRecordName = "CRYST1";
    RKString a = RKString("%1").arg(_cell->a(), 9, 'f', 3, ' ');
    RKString b = RKString("%1").arg(_cell->b(), 9, 'f', 3, ' ');
    RKString c = RKString("%1").arg(_cell->c(), 9, 'f', 3, ' ');
    RKString alpha = RKString("%1").arg(_cell->alpha() * 180.0 / M_PI, 7, 'f', 2, ' ');
    RKString beta = RKString("%1").arg(_cell->beta() * 180.0 / M_PI, 7, 'f', 2, ' ');
    RKString gamma = RKString("%1").arg(_cell->gamma() * 180.0 / M_PI, 7, 'f', 2, ' ');

    RKString spaceGroupString = _spacegroup.spaceGroupSetting().HMString().leftJustified(11, ' ', true);
    RKString zValue = RKString("%1").arg(_cell->zValue()).rightJustified(4, ' ', true);

    RKString line = spaceGroupRecordName + a + b + c + alpha + beta + gamma + " " + spaceGroupString + zValue + "\n";
    outputString += line;
  }

  int counter = 1;
  for(const std::shared_ptr<SKAsymmetricAtom> &atom : _atoms)
  {
    int atomicNumber = atom->elementIdentifier();
    SKElement element = PredefinedElements::predefinedElements[atomicNumber];
    RKString elementSymbol =  element._chemicalSymbol.rightJustified(2, ' ', true);
    RKString atomRecordName = "ATOM  ";
    RKString atomSerialNumber = RKString::number(counter).rightJustified(5, ' ', true);
    RKString atomName = elementSymbol;
    RKString remotenessIndicator = RKString(atom->remotenessIndicator());
    RKString branchIndicator = RKString(atom->branchDesignator());
    RKString alternateLocationIndicator = RKString(" ");
    RKString residueName = atom->residueName().rightJustified(3, ' ', true);
    RKString chainIdentifier = RKString(atom->chainIdentifier());
    RKString residueSequenceNumber = RKString::number(atom->residueSequenceNumber()).rightJustified(4, ' ', true);
    RKString codeForInsertionOfResidues = RKString(atom->codeForInsertionOfResidues());
    RKString orthogonalCoordinatesForX =  RKString("%1").arg(atom->position().x - _origin.x, 8, 'f', 3, ' ');
    RKString orthogonalCoordinatesForY =  RKString("%1").arg(atom->position().y - _origin.y, 8, 'f', 3, ' ');
    RKString orthogonalCoordinatesForZ =  RKString("%1").arg(atom->position().z - _origin.z, 8, 'f', 3, ' ');
    RKString occupancy =  RKString("%1").arg(atom->occupancy(), 6, 'f', 2, ' ');
    RKString isotropicBFactor =  RKString("%1").arg(atom->temperaturefactor(), 6, 'f', 2, ' ');
    RKString segmentIdentifier = atom->segmentIdentifier().rightJustified(4, ' ', true);
    RKString charge = RKString("  ");
    RKString line = atomRecordName + atomSerialNumber + " " + atomName + remotenessIndicator + branchIndicator +
                   alternateLocationIndicator + residueName + " " + chainIdentifier + residueSequenceNumber +
                   codeForInsertionOfResidues + "   " + orthogonalCoordinatesForX + orthogonalCoordinatesForY +
                   orthogonalCoordinatesForZ + occupancy + isotropicBFactor + "      " +
                   segmentIdentifier + elementSymbol + charge + "\n";
    outputString += line;
    counter += 1;
  }

  outputString += "END\n";

  return outputString;
}
